### ISSUE TITLE
Resource cannot be found

### ISSUE THREAD

**Issue by clarity99** [junalmeida/docker-mono-web#3]
I tried running this under docker for mac. docker-compose up in sample dir, starts ok, then when going to localhost I get this:

Application Exception
Runtime error
The resource cannot be found.
Description: HTTP 404.The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable. Please review the following URL and make sure that it is spelled correctly.

Details: No virtual path information available.

Exception stack trace:
Version Information: 5.20.1.19 (tarball Thu Apr 11 09:07:22 UTC 2019); ASP.NET Version: 4.0.30319.42000

in logs I see:
webapp    | 2019-04-21 11:44:38,459 CRIT Set uid to user 0
webapp    | 2019-04-21 11:44:38,460 INFO supervisord started with pid 1
webapp    | 2019-04-21 11:44:39,465 INFO spawned: 'mono' with pid 8
webapp    | 2019-04-21 11:44:39,467 INFO spawned: 'nginx' with pid 9
webapp    | 2019-04-21 11:44:40,498 INFO success: mono entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
webapp    | 2019-04-21 11:44:40,500 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by junalmeida** [comment]
I suppose that docker for Mac works the same way as docker for Windows, which doesn't work sharing a folder in the host outside user's folder. Please check if this is the case. Ssh into your container and check if the sample dist folder exists inside it.

**Comment by clarity99** [comment]
I figured it out, I had to go to /Home url, then it worked. Seems somehow the default pages in the sample are not working.
