### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by petriusus** [junalmeida/docker-mono-web#4]
First of all, thank you for making this docker template (or whatever it is called).

I just wondered how to get started. This is what i have tried on my ubuntu machine:

`docker build https://github.com/junalmeida/docker-mono-web.git`
` sudo docker run -i -t [id]`

This is what i get:
`Directory /etc/mono/pools does not exist.`

**Comment by junalmeida** [comment]
Hello @petriusus 
The easiest way to test is using the `docker-compose` inside sample folder.

https://github.com/junalmeida/docker-mono-web/tree/master/sample

`docker-compose up -d`

**Comment by junalmeida** [comment]
My recommended way for a production use is to build your Dockerfile that inherits from mine, building and moving your files.
