### ISSUE TITLE
did mono support webforms in dotnet framework 4.7.2

### ISSUE THREAD

**Issue by AmrElshaer** [junalmeida/docker-mono-web#9]
I want to run webForms in Linux but it gives me an error .
Could not resolve type from typeref expected class System.Web.UI.ScriptResourceMapping in assembly System.Web.Extensions Version=4.0.0.0 in mono with webforms

**Comment by junalmeida** [comment]
Hi @AmrElshaer, thanks for your question but it is better suitable for the mono project itself. 

Please check https://www.mono-project.com/docs/about-mono/compatibility/

**Comment by AmrElshaer** [comment]
I can't find the suitable docker image for mono to work with web Forms
![image](https://user-images.githubusercontent.com/50411156/206842275-49fa620b-83b8-4106-84f0-4ad45355a01d.png)

**Comment by junalmeida** [comment]
@AmrElshaer I suggest you try a basic Hello World project to verify your setup is ok and isolate the problem. Maybe try the sample app in this repository.
